### ISSUE TITLE
Definitie terminologiebron

### ISSUE THREAD

**Issue by ivozandhuis** [netwerk-digitaal-erfgoed/requirements-terminologiebronnen#2]
Is een terminologiebron een (statische) set termen, of een zoeksysteem waarmee (dynamisch) de termen kunnen worden gevonden? Als ik de requirements nu lees, is de AAT niet een terminologiebron, maar het SPARQL endpoint van de AAT wel. Ik weet niet of het verschil belangrijk is, zo niet: issue negeren :-D. Maar in mijn document maak ik dat onderscheid impliciet wel door te zeggen dat je een (statische) terminologiebron wel (dynamisch) moet publiceren.

**Comment by sdevalk** [comment]
Ik begrijp je punt! Bij de definitie van een terminologiebron ben ik uitgegaan van [DERA](https://dera.netwerkdigitaalerfgoed.nl/index.php/Id-eba9fe53-4f0d-3e21-4bba-cc33b7676221):

> Een bron die bestaat uit gecontroleerde termen. Thesauri en trefwoordenlijsten zijn voorbeelden van terminologiebronnen (ontleend aan het ABC Digitaal Erfgoed van DEN).

De definitie doet geen uitspraak over de vorm of wijze van aanbieden (zoals een statische set of dynamisch doorzoekbaar). Een bron die enkel statisch beschikbaar is, is dan ook een geldige terminologiebron, en een bron die doorzoekbaar is via een SPARQL-endpoint, is eveneens een geldige terminologiebron. Alleen in het eerste geval - de statische set - dient de bronhouder extra werk te verzetten om de bron beter bruikbaar te maken voor anderen (c.q. applicaties). Het onderscheid dat jij maakt is dus relevant.

**Comment by ivozandhuis** [comment]
Dan lijkt me de issue gesloten
