### ISSUE TITLE
Potentiele ambiguiteit met cm-implementation-guidelines

### ISSUE THREAD

**Issue by ivozandhuis** [netwerk-digitaal-erfgoed/requirements-terminologiebronnen#3]
Ik zie geen potentiele misverstanden als ik de tekst in [section 2.3](https://github.com/netwerk-digitaal-erfgoed/cm-implementation-guidelines#23-publishing-terminology-sources) en de requirements lees. Zou je voor mij willen kijken of jij dat ook zo ziet?

**Comment by sdevalk** [comment]
Ik zal dit nagaan! 👍🏻

**Comment by sdevalk** [comment]
@ivozandhuis (excuses – dr. Zandhuis):

Bij het lezen van de [implementation guidelines](https://github.com/netwerk-digitaal-erfgoed/cm-implementation-guidelines#23-publishing-terminology-sources) en de [requirements](https://netwerk-digitaal-erfgoed.github.io/requirements-terminologiebronnen) zie ik twee aandachtspunten:

1. De implementation guidelines stellen bij [2.3.2](https://github.com/netwerk-digitaal-erfgoed/cm-implementation-guidelines#232-technology-and-datamodel):

> This metadata must be expressed according to a specific RDF metadata model, preferably Simple Knowledge Organization System (SKOS) or Schema.org.

SKOS en Schema.org zijn zeker geschikt, maar de [requirements](https://netwerk-digitaal-erfgoed.github.io/requirements-terminologiebronnen/#3) spreken geen voorkeur uit voor een bepaald metadatamodel ('metadatastandaard'): "Door de verscheidenheid aan standaarden, soorten termen en toepassingsmogelijkheden is het mogelijk noch wenselijk om bepaalde standaarden voor te schrijven."

Wellicht kunnen de implementation guidelines 'for example' gebruiken in plaats van 'preferably'?

2. De implementation guidelines stellen bij [2.3.3](https://github.com/netwerk-digitaal-erfgoed/cm-implementation-guidelines#233-cooperation):

> For example about the way in which collection managers can propose changes to terms to sources: this should follow a uniform process.

De [requirements](https://netwerk-digitaal-erfgoed.github.io/requirements-terminologiebronnen/#9) stellen dat "een terminologiebron een manier [dient] te hebben waarmee een collectiebeheerder wijzigingsvoorstellen kan indienen", maar niet dat bronnen een uniform proces zouden moeten volgen: "Een terminologiebron bepaalt dit zelf." Deze invulling van de requirement moet echter nog verder bediscussieerd worden. Wellicht dat de requirement 'as-is' blijft, wellicht dat er alsnog gepleit wordt voor een uniform proces (waarbij dan de vraag beantwoord moet worden hoe dat proces eruit ziet – dat is nu niet gedefinieerd).

Wellicht kunnen de implementation guidelines de woorden 'should follow' iets afzwakken, bijvoorbeeld door op te merken dat bronnen 'idealiter' of 'bij voorkeur' een uniform proces volgen?

**Comment by ivozandhuis** [comment]
Dankjewel voor je heldere review, inclusief voorstellen voor aanpassing (dat is pas handig).
