### ISSUE TITLE
Remove disccusion point about need for SPARQL

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/requirements-terminologiebronnen#7]
Our current practice is to require the terminology source to be published through a SPARQL endpoint. We have no support for other APIs, we should remove the discussion point in the text we suggests we are still considering support for other APIs.

**Comment by ddeboer** [comment]
Apparently it was already removed in b84ebb4f6da0de317f09504454fb82720c7beec1, but that failed to deploy.
